// <auto-generated />
namespace SecretSanta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MemberAndGroups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MemberAndGroups));
        
        string IMigrationMetadata.Id
        {
            get { return "201511261849010_MemberAndGroups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
